name: cashcase
description: "Cashcase - Official Flutter Client"
version: 1.0.27+27

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash:
  logging:
  go_router:
  provider:
  responsive_builder:
  upgrader:
  intl:
  google_fonts:
  easy_date_timeline:
  either_dart:
  sortedmap:
  flutter_keyboard_visibility:
  chips_choice:
  calendar_date_picker2:
  animated_digit: 
  sqflite:
  uuid:
  flutter_heatmap_calendar: ^1.0.5
  flutter_file_dialog:

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  # background_image: "assets/splash.png"
  android_12:
    color: "#000000"
    # background_image: "assets/splash.png"
  ios: true
