name: cashcase
description: "Cashcase - Official Flutter Client"
publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash:
  logging:
  go_router:
  provider:
  responsive_builder:
  upgrader:
  internet_connection_checker_plus:
  pretty_dio_logger:
  dio_smart_retry:
  jwt_decoder:
  intl:
  google_fonts:
  easy_date_timeline:
  auto_size_text:
  word_generator:
  flutter_secure_storage:
  action_slider:
  either_dart:
  sortedmap:
  flutter_keyboard_visibility:
  pointycastle:
  encrypt:
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  # background_image: "assets/splash.png"
  android_12:
    color: "#000000"
    # background_image: "assets/splash.png"
  ios: true
